"""add_notifications_table

Revision ID: 1552ff288b29
Revises: 37ccc2cc63a7
Create Date: 2026-01-07 14:10:54.972173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1552ff288b29'
down_revision: Union[str, None] = '37ccc2cc63a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
